// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('❌ Supabase Configuration Missing!');
  console.error('');
  console.error('Please create a .env.local file in your project root with:');
  console.error('');
  console.error('VITE_SUPABASE_URL=https://your-project-id.supabase.co');
  console.error('VITE_SUPABASE_PUBLISHABLE_KEY=your-anon-key');
  console.error('');
  console.error('To get your credentials:');
  console.error('1. Go to https://app.supabase.com/');
  console.error('2. Select your project (ID: bqszeumafidxtywajanm)');
  console.error('3. Go to Settings → API');
  console.error('4. Copy the Project URL and anon/public key');
  console.error('');
  console.error('After adding the file, restart your dev server!');
}

if (!SUPABASE_URL) {
  throw new Error(
    'Missing env.VITE_SUPABASE_URL. Please create a .env.local file with your Supabase credentials.'
  );
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing env.VITE_SUPABASE_PUBLISHABLE_KEY. Please create a .env.local file with your Supabase credentials.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});